### ISSUE TITLE
Need complete judge_buider coding

### ISSUE THREAD

**Issue by slhmy** [OJ-lab/judger#103]

**Comment by KanadeSiina** [comment]
Afaic, the judge_builder now copy ( and depackage ) the package to a runtime path. It seems that everything is ok for `builder`. If we want to run the whole process, it is enough that it just be a "builder".

Then a simple judging process will perform as follows: Build -> Run the test case in a series -> Return the final result.

What feature should be added to builder?

**Comment by slhmy** [comment]
> Afaic, the judge_builder now copy ( and depackage ) the package to a runtime path. It seems that everything is ok for `builder`. If we want to run the whole process, it is enough that it just be a "builder".
> 
> Then a simple judging process will perform as follows: Build -> Run the test case in a series -> Return the final result.
> 
> What feature should be added to builder?

I'm not sure I have done so well with ICPC style packages, there might be misunderstandings.
Otherwise, builder should have a following output struct which can proceed judges after builds (I'm using `()` instead), this proceeder(or we need a better name) should be also build with builder, the builder read infos from files of paths, to know which validator will be used and what testcases we have got.

**Comment by KanadeSiina** [comment]
> > Afaic, the judge_builder now copy ( and depackage ) the package to a runtime path. It seems that everything is ok for `builder`. If we want to run the whole process, it is enough that it just be a "builder".
> > Then a simple judging process will perform as follows: Build -> Run the test case in a series -> Return the final result.
> > What feature should be added to builder?
> 
> I'm not sure I have done so well with ICPC style packages, there might be misunderstandings. Otherwise, builder should have a following output struct which can proceed judges after builds (I'm using `()` instead), this proceeder(or we need a better name) should be also build with builder, the builder read infos from files of paths, to know which validator will be used and what testcases we have got.

Ok, it helps me a lot. I will make more study on the package structure.

**Comment by slhmy** [comment]
Closing this issue for it's currently implemented.
