### ISSUE TITLE
A better way for test program saving is necessary

### ISSUE THREAD

**Issue by KanadeSiina** [OJ-lab/judger#85]
In the building of the judger, some test programs are built to test it. However, some libraries are necessary for this process, while some binary files are built locally for it.

In fact, all these test files are redundant for this repository. We need to find a way so that it can be well maintained, which means that:

* Do not store the binary files in the repository.
* Do not store the `testlib.h` library in the repository.
* The testing process of the judger can be done smoothly both in developing environment and github ci workflow.

Meanwhile, I hope that it is easy to build the development environment from scratch.

Some changes may be applied to the `test-program` folder.

**Comment by slhmy** [comment]
`test-program` is supposed to be moved into https://github.com/OJ-lab/judger-test-collection.

**Comment by KanadeSiina** [comment]
The structure now seems enough for developing, thanks for your help.
